apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-opa-policy
  labels:
    {{- include "opa.labels" . | nindent 4 }}
data:
  apikey-policy.rego: |
    package myapp

    default allow = false

    resp := http.send({
      "method": "GET",
      "url": "http://webdis.default.svc.cluster.local:7379/GET/myapp_allowlist",
      "headers": {"Content-Type": "application/json"},
      "force_json_decode": true
    })

    allowlist := json.unmarshal(resp.body.GET) if {
       resp.status_code == 200
       resp.body != ""
    }

    key_allowed(key) if {
      keys := {k | k := key; allowlist[key]}
      key in keys
    }

    path_allowed(token, request_path) if {

        allowed_paths := allowlist[token]
        some allowed_path in allowed_paths
        startswith(request_path, allowed_path)
    }

    # Main allow rule
    allow if {
      parsed_query := input.parsed_query 

      token := input.parsed_query.authorization
      startswith(token, "Bearer ")
      api_key := substring(token, 7, -1)
      key_allowed(api_key)

      path := parsed_query.path
      path_allowed(api_key, path)
    }

    allow if {
      input.parsed_query.path == "/"
    }
